=== nationalarchives/da-transform-schemas/json-schemas/tdr-to-tre-retry-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "version": {
        "type": "string"
      },
      "timestamp": {
        "type": "string"
      },
      "UUIDs": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "TDR-UUID": {
                "type": "string"
              }
            },
            "required": [
              "TDR-UUID"
            ]
          },
          {
            "type": "object",
            "properties": {
              "TRE-UUID": {
                "type": "string"
              }
            },
            "required": [
              "TRE-UUID"
            ]
          },
          {
            "type": "object",
            "properties": {
              "TDR-UUID": {
                "type": "string"
              }
            },
            "required": [
              "TDR-UUID"
            ]
          }
        ]
      },
      "producer": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "process": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "environment": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "process",
          "type",
          "environment"
        ]
      },
      "parameters": {
        "type": "object",
        "properties": {
          "TDR": {
            "type": "object",
            "properties": {
              "resource": {
                "type": "object",
                "properties": {
                  "resource-type": {
                    "type": "string"
                  },
                  "access-type": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                },
                "required": [
                  "resource-type",
                  "access-type",
                  "value"
                ]
              },
              "resource-validation": {
                "type": "object",
                "properties": {
                  "resource-type": {
                    "type": "string"
                  },
                  "access-type": {
                    "type": "string"
                  },
                  "validation-method": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                },
                "required": [
                  "resource-type",
                  "access-type",
                  "validation-method",
                  "value"
                ]
              },
              "number-of-retries": {
                "type": "string"
              },
              "reference": {
                "type": "string"
              }
            },
            "required": [
              "resource",
              "resource-validation",
              "number-of-retries",
              "reference"
            ]
          }
        },
        "required": [
          "TDR"
        ]
      }
    },
    "required": [
      "version",
      "timestamp",
      "UUIDs",
      "producer",
      "parameters"
    ]
  }

=== nationalarchives/da-transform-schemas/json-examples/tdr-to-tre-retry-schema.json
{
    "version": "ABCDEFGHIJKLMNOPQRSTUV",
    "timestamp": "ABCDEFGHIJKLM",
    "UUIDs": [
      {
        "TDR-UUID": "ABCDEFGHIJKLMNO"
      },
      {
        "TRE-UUID": "ABCDEFGHIJKLM"
      },
      {
        "TDR-UUID": "ABCDEFGH"
      }
    ],
    "producer": {
      "name": "ABCDEFGHIJKLMNOPQRSTUV",
      "process": "ABCDEFGHIJKLMNOPQ",
      "type": "ABCDEFGHIJ",
      "environment": "ABCDEF"
    },
    "parameters": {
      "TDR": {
        "resource": {
          "resource-type": "ABCDEFGHIJKLMNOPQRSTUVW",
          "access-type": "ABCDEFGHIJKLMNOPQRSTUVWX",
          "value": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC"
        },
        "resource-validation": {
          "resource-type": "ABCDEFGHIJKLMNOPQRSTUV",
          "access-type": "ABCDE",
          "validation-method": "ABCDEFGHIJ",
          "value": "ABCDEFGHIJKLMNOPQ"
        },
        "number-of-retries": "ABCDEFGHIJKLMNOPQRSTUVWX",
        "reference": "ABCDEFGHIJKL"
      }
    }
  }

=== nationalarchives/da-transform-schemas/json-examples/tdr-to-tre-example.json
{
    "version": "ABCD",
    "timestamp": "ABCDEFGHIJKLMNOPQ",
    "UUIDs": [
      {
        "TDR-UUID": "ABCDEFGH"
      }
    ],
    "producer": {
      "name": "ABCDEFGHIJKLMNOP",
      "process": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC",
      "type": "ABCDEFGHIJKLMNOPQRST",
      "environment": "ABCDEFGHIJKLMNOPQRSTUV"
    },
    "parameters": {
      "TDR": {
        "resource": {
          "resource-type": "ABCDEFGHIJKLMNOPQRS",
          "access-type": "ABCDEFGHIJKLMNO",
          "value": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC"
        },
        "resource-validation": {
          "resource-type": "ABCDEFGHIJKLM",
          "access-type": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC",
          "validation-method": "ABCDEFGHIJ",
          "value": "ABCDEFGHIJKLMNOPQRSTUVWXYZAB"
        },
        "number-of-retries": "ABCDEFGHIJKLMNOPQRSTUVWXYZAB",
        "reference": "ABCDEFGHIJKLMNOP"
      }
    }
  }
