=== nationalarchives/da-transform-schemas/tre_schemas/tre-event.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nationalarchives.gov.uk/da-transform/tre/schemas/tre-event",
    "type": "object",
    "properties": {
        "version": {
            "type": "string"
        },
        "timestamp": {
            "type": "integer"
        },
        "UUIDs": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "patternProperties": {
                    "^[a-zA-Z0-9_-]+-UUID$": {
                        "type": "string",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    }
                },
                "additionalProperties": false
            },
            "additionalProperties": false
        },
        "producer": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "process": {
                    "type": ["string", "null"]
                },
                "type": {
                    "type": [
                        "string",
                        "null"
                    ],
                    "enum": [
                        "judgment",
                        "standard",
                        null
                    ]
                },
                "environment": {
                    "type": ["string", "null"]
                },
                "event-name": {
                    "type": "string",
                    "pattern": "^[.a-zA-Z0-9_-]+$"
                },
                "version": {
                    "type": ["string", "object"]
                }
            },
            "required": [
                "name",
                "process",
                "type",
                "environment",
                "event-name"
            ],
            "additionalProperties": false
        },
        "parameters": {
            "type": "object"
        }
    },
    "required": [
        "version",
        "timestamp",
        "UUIDs",
        "producer",
        "parameters"
    ],
    "additionalProperties": false
}

=== nationalarchives/da-transform-schemas/design/options/2022-08-18/DTE-276/02-tre-to-tre-internal.json
{
  "version": "0.0.2",
  "timestamp": 1661155079974733000,
  "UUIDs": [
    {
      "TDR-UUID": "45be6508-b693-441d-a0d6-defb3f41c1fb"
    },
    {
      "TRE-UUID": "13b5e0a5-4944-46b1-abd2-f01f5c6f9abb"
    },
    {
      "TRE-UUID": "03ef1432-16de-4f6b-8fbc-3afd341736eb"
    }
  ],
  "producer": {
    "environment": "dev",
    "name": "TRE",
    "process": "dev-tre-validate-bagit",
    "event-name": "bagit-validated",
    "type": "judgment"
  },
  "parameters": {
    "bagit-validated": {
      "reference": "TDR-1234-ABCD",
      "s3-bucket": "dev-tre-common-data",
      "s3-bagit-name": "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD.tar.gz",
      "number-of-retries": 0,
      "errors": [],
      "s3-object-root": "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD",
      "validated-files": {
        "path": "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD",
        "root": [
          "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD/bag-info.txt",
          "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD/manifest-sha256.txt",
          "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD/bagit.txt",
          "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD/file-ffid.csv",
          "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD/file-metadata.csv",
          "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD/file-av.csv"
        ],
        "data": [
          "consignments/judgment/TDR-1234-ABCD/0/TDR-1234-ABCD/data/test.docx"
        ]
      }
    }
  }
}

=== nationalarchives/da-transform-schemas/json-examples/dri-preingest-sip-available.json
{
  "version": "0.0.7-alpha",
  "timestamp": 1663666690368414700,
  "UUIDs": [
    {
      "test-producer-UUID": "9c6d25c1-c8c9-495a-be0b-91e7af7b2083"
    },
    {
      "TRE-UUID": "e62f13af-2b48-4917-974c-b94955d76c87"
    },
    {
      "TRE-UUID": "3248d12c-aed4-49a5-9514-80ece1d41e36"
    },
    {
      "TRE-UUID": "e7667156-02f5-48b0-8a4b-a4ded7aa3c71"
    }
  ],
  "producer": {
    "environment": "dev",
    "name": "TRE",
    "process": "dev-tre-dri-preingest-sip-generation",
    "event-name": "dri-preingest-sip-available",
    "type": "standard"
  },
  "parameters": {
    "dri-preingest-sip-available": {
      "reference": "TDR-2022-NQ3",
      "s3-folder-url": "https://dev-tre-dpsg-out.s3.amazonaws.com/consignments/standard/TDR-2022-NQ3/9c6d25c1-c8c9-495a-be0b-91e7af7b2083/TDR-2022-NQ3/sip/MOCKA101Y22TBNQ3.tar.gz?X-Amz-Algorithm=AWS4-HMAC-...",
      "s3-sha256-url": "https://dev-tre-dpsg-out.s3.amazonaws.com/consignments/standard/TDR-2022-NQ3/9c6d25c1-c8c9-495a-be0b-91e7af7b2083/TDR-2022-NQ3/sip/MOCKA101Y22TBNQ3.tar.gz.sha256?X-Amz-Algorithm=AWS4-HMAC-...",
      "file-type": "TAR"
    }
  }
}

=== nationalarchives/da-transform-schemas/design/options/2022-08-18/DTE-276/01-tdr-to-tre.json
{
  "version": "1.0.0",
  "timestamp": 1661155064747274000,
  "UUIDs": [
    {
      "TDR-UUID": "45be6508-b693-441d-a0d6-defb3f41c1fb"
    }
  ],
  "producer": {
    "environment": "dev",
    "name": "TDR",
    "process": "da-transform-terraform-modules/testing/step_functions/validate_bagit",
    "event-name": "consignment-export",
    "type": "judgment"
  },
  "parameters": {
    "consignment-export": {
      "resource": {
        "resource-type": "Object",
        "access-type": "url",
        "value": "https://dev-te-testdata.s3.amazonaws.com/consignments/judgment/TDR-1234-ABCD.tar.gz?X-Amz-..."
      },
      "resource-validation": {
        "resource-type": "Object",
        "access-type": "url",
        "validation-method": "SHA256",
        "value": "https://dev-te-testdata.s3.amazonaws.com/consignments/judgment/TDR-1234-ABCD.tar.gz.sha256?X-Amz-..."
      },
      "number-of-retries": 0,
      "reference": "TDR-1234-ABCD"
    }
  }
}

=== nationalarchives/da-transform-schemas/json-examples/validate-bagit-bagit-validated.json
{
  "version": "1.0.0",
  "timestamp": 1661340417609575000,
  "UUIDs": [
    {
      "TDR-UUID": "c73e5ca7-cf87-442a-8248-e05f81361ae0"
    },
    {
      "TRE-UUID": "ec506d7f-f531-4e63-833e-841918105e41"
    },
    {
      "TRE-UUID": "3c1db304-090f-4b19-abfc-8618cc0e5875"
    }
  ],
  "producer": {
    "environment": "dev",
    "name": "TRE",
    "process": "dev-tre-validate-bagit",
    "event-name": "bagit-validated",
    "type": "standard"
  },
  "parameters": {
    "bagit-validated": {
      "reference": "ABC-1234-DEF",
      "s3-bucket": "dev-tre-common-data",
      "s3-bagit-name": "consignments/standard/ABC-1234-DEF/c73e5ca7-cf87-442a-8248-e05f81361ae0/ABC-1234-DEF.tar.gz",
      "s3-object-root": "consignments/standard/ABC-1234-DEF/c73e5ca7-cf87-442a-8248-e05f81361ae0/ABC-1234-DEF",
      "validated-files": {
        "path": "consignments/standard/ABC-1234-DEF/c73e5ca7-cf87-442a-8248-e05f81361ae0/ABC-1234-DEF",
        "root": [
          "consignments/standard/ABC-1234-DEF/c73e5ca7-cf87-442a-8248-e05f81361ae0/ABC-1234-DEF/bagit.txt",
          "consignments/standard/ABC-1234-DEF/0/ABC-1234-DEF/manifest-sha256.txt"
        ],
        "data": [
          "consignments/standard/ABC-1234-DEF/c73e5ca7-cf87-442a-8248-e05f81361ae0/ABC-1234-DEF/data/content/foo.docx",
          "consignments/standard/ABC-1234-DEF/c73e5ca7-cf87-442a-8248-e05f81361ae0/ABC-1234-DEF/data/content/bar.png"
        ]
      }
    }
  }
}
